name: Node CI

on:
  push:
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: submodules update
      run: git submodule update --init --recursive
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
